from types import SimpleNamespace

SSH_USER = "administrator"
SSH_IP = "146.244.98.51"
SSH_PASSWORD = "clearpath"
CLIENT_DIRECTORY = "~/husky"
SERVER_DIRECTORY = f"{SSH_USER}@{SSH_IP}:{CLIENT_DIRECTORY}"
SERVER_DIRECTORY_AS_SEEN_FROM_SERVER = CLIENT_DIRECTORY

HUSKY_CONFIG = SimpleNamespace(
    SSH_USER=SSH_USER,
    SSH_IP=SSH_IP,
    SSH_PASSWORD=SSH_PASSWORD,
    CLIENT_DIRECTORY=CLIENT_DIRECTORY,
    SERVER_DIRECTORY=SERVER_DIRECTORY,
    SERVER_DIRECTORY_AS_SEEN_FROM_SERVER = SERVER_DIRECTORY_AS_SEEN_FROM_SERVER
)