from types import SimpleNamespace

SSH_USER = "administrator"
SSH_IP = "146.244.98.51"
SSH_PASSWORD = "clearpath"
CLIENT_DIRECTORY = "/home/dicelabs/husky"
SERVER_DIRECTORY = "/home/administrator/husky"
SCP_DIRECTORY = f"{SSH_USER}@{SSH_IP}:{SERVER_DIRECTORY}"

HUSKY_CONFIG = SimpleNamespace(
    SSH_USER=SSH_USER,
    SSH_IP=SSH_IP,
    SSH_PASSWORD=SSH_PASSWORD,
    CLIENT_DIRECTORY=CLIENT_DIRECTORY,
    SERVER_DIRECTORY=SERVER_DIRECTORY,
    SCP_DIRECTORY=SCP_DIRECTORY
)